---
title: "FAQ"
---

## When will I get feedback for assessment 1 (Problem Sets)

Immediate feedback is available for every commit to the Github Repository for each assessment (via the actions tab).  Further feedback and marks will also be given overall four working weeks after the deadline (not accounting for the two weeks of winter holidays), for the week of January 19th 2026

## What is the deadline for problem set assessments?

Submission Deadline: **15.00 on 2025-12-11 (Thursday, 11 Dec)**, by which time and date all of your problems sets must be completed and submitted to gain credit for them.

This is the **ultimate** deadline for problem sets, set by the university and it can be found in the SQ4007 Assessment (problem set) document linked on the [Harper Adams module page](https://vle.harper-adams.ac.uk/course/view.php?id=282).

However, there are several **suggested** deadlines for each problem set, which might cause confusion. The weekly deadlines on the schedule are the (strongly) suggested pace of work to keep up with the module. They are not the ultimate deadline for the problem set assessment (i.e. you can submit your problem sets and still gain credit up to the ultimate deadline).

## Can I work ahead on the problem sets?

Yes, you *can* work ahead on the problem sets, in the sense it is possible and you are not restricted from doing so if they have already been posted in advance. However, we'd prefer you consider doing them on the suggested pace of work, as this will allow you to work as a cohort and make full use of the co-coding sessions during classtime and to interact with your classmates.


------------------------------------------------------------------------

::::: columns
::: {.column width="28%"}
```{=html}
<iframe width="200" height="125" src="https://www.youtube.com/embed/WVPIzkYjxvk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
:::

::: column
## How do I log into The Sandbox coding environment?
:::
:::::

------------------------------------------------------------------------

::::: columns
::: {.column width="28%"}
```{=html}
<iframe width="200" height="125" src="https://www.youtube.com/embed/YnLlfTy-PRw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
:::

::: column
## How do I submit my problem set assignments?
:::
:::::

------------------------------------------------------------------------

## Flipped Classroom: Can I still come to lecture if I don't watch the videos and go through the notes for that week before class?

Yes, of course you can and should! But...

The point of the flipped classroom is to maximise the time spent in class discussing and solving problems. If you don't watch the videos and go through the notes for that week before class, you will miss out on this and potentially fall behind while others are getting on with their problem set work during classtime.

------------------------------------------------------------------------

## Why do I keep running out of GitHub Codespace time?

There are two types of Codespaces usage: compute and storage.
Each month as you use Codespaces, your compute and storage usage is deducted from the quota of free usage that's included in your personal GitHub account until either compute or storage is consumed. 

Once one of those limits is reached, your use of GitHub Codespaces will be restricted. You will not be able to create new Codespaces or open existing Codespaces, until the monthly quota renews in the following month. 

Standard allowance is 15GB-hours of storage per month and 120 hours of compute time. 
If you sign up to [GitHub Education](https://github.com/education), this increases to 20GB-hours and 180 hours of compute time. **Highly recommend doing this - it can take 72 hours to be confirmed following application**


#### How can I get the most out of my Codespace time?
Some tips from GitHub for making allowed usage go further: 

* Your codespaces consume compute usage while they are running. If you're not using a codespace, stopping the codespace prevents unnecessary compute usage. [See Stopping and starting a codespace](https://docs.github.com/en/codespaces/developing-in-a-codespace/stopping-and-starting-a-codespace).

* You can reduce the idle timeout for Codespaces in your personal settings to less than the default 30 minutes. This will shorten the period of inactivity before your codespaces are automatically stopped. This can save on compute usage. [See Setting your timeout period for GitHub Codespaces](https://docs.github.com/en/codespaces/setting-your-user-preferences/setting-your-timeout-period-for-github-codespaces).

* Your codespaces consume storage while they exist. You should delete a codespace you have finished using and know that you will not use again. [See Deleting a codespace](https://docs.github.com/en/codespaces/developing-in-a-codespace/deleting-a-codespace).

* Configure your retention period to ensure codespaces you forget to delete are deleted automatically. The default retention period is 30 days. [See Configuring automatic deletion of your codespaces](https://docs.github.com/en/codespaces/setting-your-user-preferences/configuring-automatic-deletion-of-your-codespaces).

* Visual Studio Code extensions consume storage. Make sure you are only installing extensions that you need. You can find out how much space is being used by extensions by running this command in your codespace.


`du -h -s ~/.vscode-remote/extensions ` 

* Monitor your compute and storage usage by going to your [billing page on GitHub](https://github.com/settings/billing), and reviewing the figures in the "Codespaces" section.

------------------------------------------------------------------------

## Large file detected! Week 8 Movies - Large file error

If you've tried the week 8 problem set and found yourself getting an error when trying to commit your work to your github repository (*or are about to start this problem and want to avoid the error altogether*), follow the steps [here](pdfs/Wk8_large_file_github_issue.pdf).

------------------------------------------------------------------------

## Can I just code on my own computer?

The short answer is, heck yeah!! But, you will still need to use our Github Codespaces to submit your work.

However, installing and configuring programming and editing software on your own computer is sometimes complicated and irritating, even for very experienced people. Configuring all the tools we will be using in The Sandbox to be exactly the same on your own computer, operating system, etc., will require advanced skills. Still, you can do it if you want to; most of the tools are open source and free and will work for most tasks. Also, we are here to help support you if you want to try.

If you want to explore this path, here are the main things you need to do:

For a start...

-   Download and install Python (\> v3.11): <https://www.python.org/downloads/>
-   Download and install VS Code (other editors are okay too): <https://code.visualstudio.com/download>
-   Install C/C++ in VS Code: <https://code.visualstudio.com/docs/languages/cpp>
-   Install Git: <https://happygitwithr.com/install-git.html>
-   Install the CS50 library: <https://github.com/cs50/libcs50>

------------------------------------------------------------------------
