---
title: "Schedule"
---

🔗 ["The Sandbox" coding environment (Github Codespace)](https://classroom.github.com/a/n-LXZmS6)

This schedule is an outline of the topics, with links to all content, and assignments. Note that this may be updated as the module progresses.

+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| Week                                                                  | Topics                           | Lectures                                                                                    | Notes                                | Code                                                                | Tutorials                                                                | Problem Sets             |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| ([HAU week](https://www.harper-adams.ac.uk/documents/term-dates.pdf)) |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+:=====================================================================:+:=================================+:===========================================================================================:+:====================================:+:===================================================================:+:========================================================================:+:========================:+
| 00                                                                    | 🐍 Scratch                       | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_1.pptx)   | [📕](notes/notes_1.html "Notes 1")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src1)  |                                                                          | [🏠](homework/hw_1.html) |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(16\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 01                                                                    | 🐍 C                             | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_2.pptx)   | [📕](notes/notes_2.html "Notes 2")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src2)  | [👨‍🏫](tutorials/tutorial-week-2.html) \| [🏠](homework/hw_2.html) \| \|   |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(17\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 02                                                                    | 🐍 Arrays                        | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_3.pptx)   | [📕](notes/notes_3.html "Notes 3")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src3)  | [👨‍🏫](tutorials/tutorial-week-3.html) \| [🏠](homework/hw_3.html) \| \|   |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(18\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 03                                                                    | 🐍 Algorithms                    | ▶ [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_4.pptx) | [📕](notes/notes_4.html "Notes 4")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src4)  | [👨‍🏫](tutorials/tutorial-week-4.html) \| [🏠](homework/hw_4.html) \| \|   |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(19\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 04                                                                    | 🐍 Memory                        | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_5.pptx)   | [📕](notes/notes_5.html "Notes 5")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src5)  | [👨‍🏫](tutorials/tutorial-week-5.html) \| [🏠](homework/hw_5.html) \| \|   |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(20\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 05                                                                    | 🐍 Data structures               | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_6.pptx)   | [📕](notes/notes_6.html "Notes 6")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src6)  | [👨‍🏫](tutorials/tutorial-week-6.html) \| [🏠](homework/hw_6.html) \| \|   |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(21\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 06                                                                    | 🐍 Python                        | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_7.pptx)   | [📕](notes/notes_7.html "Notes 7")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src7)  | [👨‍🏫](tutorials/tutorial-week-7.html) \| [🏠](homework/hw_7.html) \| \|   |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(22\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| \-                                                                    | 💥 Mid term Break                | \-                                                                                          | \-                                   | \-                                                                  | \-                                                                       | \-                       |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 07                                                                    | 🐍 SQL (project group and title) | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_8.pptx)   | [📕](notes/notes_8.html "Notes 8")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src8)  | [👨‍🏫](tutorials/tutorial-week-8.html) \| [🏠](homework/hw_8.html) \| \|   |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(23\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 08                                                                    | 🐍 Web programming               | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_9.pptx)   | [📕](notes/notes_9.html "Notes 9")   | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src9)  | [👨‍🏫](tutorials/tutorial-week-9.html) \| [🏠](homework/hw_9.html) \| \|   |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(24\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 09                                                                    | 🐍 Flask (project pitch)         | [💻](https://github.com/SQ4007-2025/website/raw/refs/heads/master/lectures/slides_10.pptx)  | [📕](notes/notes_10.html "Notes 10") | [🤖](https://github.com/SQ4007-2025/website/tree/master/code/src10) | [👨‍🏫](tutorials/tutorial-week-10.html) \| [🏠](homework/hw_10.html) \| \| |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(25\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 10                                                                    | 👋 Wrap up Open lab              |                                                                                             |                                      |                                                                     |                                                                          |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(26\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 11                                                                    | 🚀 Open lab                      |                                                                                             |                                      |                                                                     |                                                                          |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(27\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
| 12                                                                    | 🚀 Open lab                      |                                                                                             |                                      |                                                                     |                                                                          |                          |
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
| \(28\)                                                                |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+
|                                                                       |                                  |                                                                                             |                                      |                                                                     |                                                                          |                          |
+-----------------------------------------------------------------------+----------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------+---------------------------------------------------------------------+--------------------------------------------------------------------------+--------------------------+

```{r echo = FALSE}
knitr::knit_exit()
```